### ISSUE TITLE
Broken markup in Python threads article 

### ISSUE THREAD

**Issue by cl0ne** [laurentluce/blog#1]
For some reason code blocks in [the article](http://www.laurentluce.com/posts/python-threads-synchronization-locks-rlocks-semaphores-conditions-events-and-queues/) start with `<pre><pre class="brush: bash; title: ; notranslate" title="">` instead of `<pre class="brush: bash; title: ; notranslate" title="">` and have only single corresponding closing tag. Screenshot is attached below.

![image](https://user-images.githubusercontent.com/271097/94059417-0ae2d080-fdeb-11ea-9b13-f05e48984d2a.png)

**Comment by laurentluce** [comment]
Upgrading wordpress has broken some of the posts.  Thanks for pointing it out.  It is now fixed.
